---

- name: GRAFANA | Manage Debian environment
  import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: GRAFANA | Manage Redhat environment
  import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: GRAFANA | Installation
  package:
    name: grafana={{ grafana_version }}*
    state: present
    update_cache: yes
  notify:
    - Restart grafana

- name: GRAFANA | Configuration
  template:
    src: "etc/grafana/grafana.ini.j2"
    dest: "/etc/grafana/grafana.ini"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart grafana

- name: GRAFANA | Manage directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ grafana_system_user }}"
    group: "{{ grafana_system_group }}"
    mode: 0755
  with_items:
    - "{{ grafana_dir_data }}"
    - "{{ grafana_dir_log }}"
    - "{{ grafana_dir_plugin }}"
    - "{{ grafana_dashboard_path }}"
